### PR TITLE
Minor CI improvments

### PR DESCRIPTION
**Pull request by ariscript**
## Confirmation
- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines](https://github.com/nullishamy/JVM/blob/main/CONTRIBUTING.MD)

### Changes

- [ ] Internal
- [ ] Feature
- [ ] Documentation
- [x] Other: CI workflow

## Description

Minor CI changes, adds names to workflows so it looks like `Generate Documentation` and not `.github/workflows/docs.yml / generate-docs`. Also makes the linting workflow not run when comments get made or edited, which cuts down on unnecessary runs.

### CODE REVIEW

**Comment by nullishamy** [comment]
Does GH actions take configs from main exclusively or can we target dev here?

**Comment by ariscript** [comment]
It checks workflow files on the branch the commit was made on. So I think the files would need to be updated on both branches, so PRs targeting either branch would use the updated file. But the docs workflow can be on main exclusively because tagged release commits should be made to main anyways.

**Comment by nullishamy** [comment]
I see. We should target dev and I will merge into main so that we don't have weird histories. I also need to sort out the Git histories as they are quite messed up due to some recent resigning and amending operations.

**Comment by ariscript** [comment]
I've changed the base to dev and rebased to fix all the conflicts.

**Comment by nullishamy** [comment]
The commit name does not follow convention >:(

**Comment by ariscript** [comment]
Fixed

**Comment by nullishamy** [comment]
Ok, LGTM.

**Pull request merged**
